[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = ["shell", "homebrew"]
targets = ["aarch64-apple-darwin"]
hosting = "github"
tap = "frankieramirez/homebrew-tap"
publish-jobs = ["homebrew"]
post-announce-jobs = ["./deploy-site"]

[[dist.extra-artifacts]]
artifacts = ["docs.json"]
build = ["cargo", "run", "--example", "docs-json", "--", "--out", "docs.json"]
